Viasofie/Viasofie/urls.py
from django.conf import settings
from django.conf.urls.static import static				#check documentatie https://docs.djangoproject.com/en/1.9/howto/static-files/
from django.conf.urls import include, url 				#function allows referencing other URLconfs
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('master.urls')),

]

"""
deze vorm van static mag enkel gerunt worden in development NIET IN PRODUCTION 
if settings.DEBUG:	 zorgt ervoor dat het static enkel gerunt wordt in development 

"""

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      #root naar mijn static files
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)      #root naar mijn media files

Viasofie/master/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # bij home url doorverwijzen naar index
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^verkoper/$', views.VerkoperView.as_view(), name='verkoper'),
    url(r'^advice/$', views.AdviceView.as_view(), name='advice'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^loggedin/$', views.Loggedin.as_view(), name='loggedin'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^resetpassword/passwordsent/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^resetpassword/$', auth_views.password_reset, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^panden/$', views.PandenView.as_view(), name='panden'),
    url(r'^pand/(?P<pk>[0-9]+)/$', views.PandDetail.as_view(), name='pand_detail'),
    url(r'partner/$', views.PartnerView.as_view(), name='partner'),
]

Viasofie/master/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

decimal = RegexValidator(r'^[0-9]+(\.[0-9]{1,5})?$', 'Enkel decimalen toegelaten bv. 0.1')
alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Enkel alphanumerische waarden toegtelaten bv. abc123  .')
alphaChar = RegexValidator(r'^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')



# _________________BEGIN GURU DOMEIN________________________

class UserProfile(models.Model):
    MY_CHOICES = (
        ('a', 'Man'),
        ('b', 'Vrouw'),
        ('c', 'Anders'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    locatie = models.CharField(max_length=140, blank=True)
    geslacht = models.CharField(max_length=1, choices=MY_CHOICES, blank=True)

    def __str__(self):
        return 'Naam : ' + str(self.user.username) + ' email: ' + str(self.user.email) + ' Locatie: ' + str(
            self.locatie) + ' Geslacht: ' + str(self.geslacht)

    def get_absolute_url(self):
        return '/profile/' + str(self.user.pk)

    @classmethod
    def create(cls, user, locatie, geslacht):
        profile = cls(user=user, locatie=locatie, geslacht=geslacht)
        profile.save()
        return profile


# ________________EINDE GURU DOMEIN ________________________

class TypeHuis(models.Model):
    class Meta:
        verbose_name_plural = "Type huizen"

    naam = models.CharField(max_length=65, validators=[alphaChar])

    def __str__(self):
        return self.naam


class Fase(models.Model):
    class Meta:
        verbose_name_plural = "Fases"

    naam = models.CharField(max_length=15)

    def __str__(self):
        return self.naam


class Status(models.Model):
    class Meta:
        verbose_name_plural = "Statussen"

    naam = models.CharField(max_length=65, validators=[alphaChar])

    def __str__(self):
        return self.naam


class Pand(models.Model):
    class Meta:
        verbose_name_plural = "Pand"
        ordering = ["user"]  # sorteren op users

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.ForeignKey(TypeHuis, on_delete=models.CASCADE)
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    straat_naam = models.CharField(max_length=255, validators=[alphaChar])
    huis_nummer = models.IntegerField()
    stad = models.CharField(max_length=255, validators=[alphaChar])
    postcode = models.IntegerField()
    prijs = models.DecimalField(max_digits=16, decimal_places=2)
    beschrijving = models.TextField()
    hits = models.IntegerField(default=0)
    profiel_foto = models.FileField('Profiel_foto', upload_to='media/', default='')

    def straat(self):
        return u'%s %s' % (self.straat_naam, self.huis_nummer)
    straat.short_description = "straat"


    def fotos(self):
        alle_fotos = Image.objects.filter(pand=self)
        return alle_fotos

    def criteria(self):
        pand_criterias = PandCriteria.objects.filter(pand=self)
        return pand_criterias

    def eigenschappen(self):
        pand_eigenschappen = PandEigenschap.objects.filter(pand=self)
        return pand_eigenschappen

    def verbruiks_type(self):
        pand_verbruiks_type = PandVerbruiksType.objects.filter(pand=self)
        return pand_verbruiks_type

    def wettelijk(self):
        pand_wettelijk = PandWettelijk.objects.filter(pand=self)
        return pand_wettelijk

    def review(self):
        pand_review = PandReview.objects.filter(pand=self)
        return pand_review

    def __str__(self):
        return self.straat_naam + ' ' + str(self.huis_nummer) + ' ' + self.stad + ' ' + str(self.postcode) + '<img src="%s"/>' % self.profiel_foto


class Image(models.Model):
    file = models.FileField('File', upload_to='media/')
    pand = models.ForeignKey('Pand', related_name='images', blank=True, null=True)

    def __str__(self):
        return self.file.url


class Criteria(models.Model):
    class Meta:
        verbose_name_plural = "Criteria's"

    naam = models.CharField(max_length=255, validators=[alphaChar])

    def __str__(self):
        return self.naam


class PandCriteria(models.Model):
    class Meta:
        unique_together = ("pand", "criteria")
        verbose_name_plural = "Pand criteria's"

    pand = models.ForeignKey(Pand, on_delete=models.CASCADE)
    criteria = models.ForeignKey(Criteria, on_delete=models.CASCADE)
    aantal = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.criteria)


class Eigenschap(models.Model):
    class Meta:
        verbose_name_plural = "Eigenschappen"

    naam = models.CharField(max_length=255, validators=[alphaChar])
    oppervlakte = models.CharField(blank=True, max_length=32, validators=[alphanumeric], default='0')
    eenheid = models.CharField(blank=True, max_length=10, default="M")

    def __str__(self):
        return self.naam


class PandEigenschap(models.Model):
    class Meta:
        verbose_name_plural = "Pand eigenschappen"

    pand = models.ForeignKey(Pand, on_delete=models.CASCADE)
    eigenschap = models.ForeignKey(Eigenschap, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pand) + ' ' + str(self.eigenschap)


class VerbruiksType(models.Model):
    class Meta:
        verbose_name_plural = "Verbruikstypen"

    naam = models.CharField(max_length=255, validators=[alphaChar])

    def __str__(self):
        return self.naam


class PandVerbruiksType(models.Model):
    class Meta:
        verbose_name_plural = "Pand verbruikstypen"

    pand = models.ForeignKey(Pand, on_delete=models.CASCADE)
    verbruik = models.ForeignKey(VerbruiksType, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pand) + ' met energievorm ' + str(self.verbruik)


class Wettelijk(models.Model):
    class Meta:
        verbose_name="wettelijke informatie"
        verbose_name_plural = "Wettelijke informaties"

    naam = models.CharField(max_length=255, validators=[alphaChar])

    def __str__(self):
        return self.naam


class PandWettelijk(models.Model):
    class Meta:
        verbose_name_plural = "Wettelijke informaties van panden"

    pand = models.ForeignKey(Pand, on_delete=models.CASCADE)
    wettelijk = models.ForeignKey(Wettelijk, on_delete=models.CASCADE, verbose_name="wettelijke informatie")
    oppervlakte = models.CharField(blank=True, max_length=32, validators=[decimal])
    eenheid = models.CharField(blank=True, max_length=10, default="M")
    jaartal = models.DateField()

    def __str__(self):
        return str(self.pand) + ' ' + str(self.wettelijk) + ' ' + str(self.jaartal)


class Review(models.Model):
    class Meta:
        verbose_name_plural = "Reviews"

    review_naam = models.CharField(max_length=255, validators=[alphaChar], verbose_name="Auteur")
    review_text = models.TextField(verbose_name="review")

    def __str__(self):
        return self.review_text+' |review door: '+self.review_naam


class PandReview(models.Model):
    class Meta:
        verbose_name_plural = "Pand reviews"

    pand = models.ForeignKey(Pand, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pand) + ' ' + str(self.review)


class Bezichtiging(models.Model):
    class Meta:
        verbose_name_plural = "Bezichtigingen"

    voornaam_bezoeker = models.CharField(max_length=255, validators=[alphaChar], verbose_name="Voornaam")
    achternaam_bezoeker = models.CharField(max_length=255, validators=[alphaChar], verbose_name="Achternaam")

    def __str__(self):
        return self.achternaam_bezoeker + ' ' + self.voornaam_bezoeker


class PandBezichtiging(models.Model):
    class Meta:
        verbose_name_plural = "Pand bezichtigingen"
        unique_together = ("pand", "bezichtiging", "datum")  # kan toch niet dat een persoon dezelfde pand meermaals op dezelfde dag bezichtig ofwel?

    pand = models.ForeignKey(Pand, on_delete=models.CASCADE)
    bezichtiging = models.ForeignKey(Bezichtiging, on_delete=models.CASCADE)
    datum = models.DateField()

    def bezichtigd(self):
        return u'%s' % self.datum
    bezichtigd.short_description = "Bezichtigd op"

    def __str__(self):
        return str(self.bezichtiging) + ' ' + str(self.pand) + ' ' + str(self.datum)


class Supportticket(models.Model):
    class Meta:
        verbose_name_plural = "Supporttickets"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    titel = models.CharField(max_length=255)
    beschrijving = models.TextField()
    datum = models.DateField()

    def gemaakt(self):
        return u'%s' % self.datum
    gemaakt.short_description = "Gemaakt op"

    def __str__(self):
        return self.titel + ' ' + self.beschrijving + ' ' + str(self.datum)

Viasofie/master/forms.py
from django.contrib.auth.models import User
from master.models import UserProfile
from django import forms


class LoginForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'email':  forms.TextInput(attrs={'class': 'w3-input w3-border w3-round-large email-field'}),
            'password': forms.PasswordInput(attrs={'class': 'w3-input w3-border w3-round-large password-field'}),
        }


class VerkoperForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'w3-input w3-border w3-round-large partner-field', 'placeholder' : 'voornaam'}),
            'last_name': forms.TextInput(attrs={'class': 'w3-input w3-border w3-round-large partner-field', 'placeholder' : 'achternaam'}),
            'email': forms.TextInput(attrs={'class': 'w3-input w3-border w3-round-large partner-field', 'placeholder' : 'email'}),
        }


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['locatie', 'geslacht']
        widgets = {
            'locatie': forms.TextInput(attrs={'class': 'w3-input w3-border w3-round-large partner-field'}),
            'geslacht': forms.TextInput(attrs={'class': 'w3-input w3-border w3-round-large partner-field'}),
        }

Viasofie/templates/master/testing/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
                <!-- CDN Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
		            <!-- FONTS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

                <!-- EXTERN CSS -->
    <link href="{% static 'master/css/base/hover.css' %}" rel="stylesheet">
    <link href="{% static 'master/css/footer/footer-with-address-and-phones.css' %}" rel="stylesheet">


            <!-- EIGEN STYLESHEETS -->
    <link href="{% static 'master/css/base/base.css' %}" rel="stylesheet">
    <title>{% block title %}Nieuwe homepage{% endblock %}</title>
</head>






<body>
    <div class="container-fluid">
        <div class="row">
                <nav class="navbar navbar-default ">
                      <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">
                                <img alt="Brand" src="{% static 'master/img/base/logo2.jpg' %}" height="50" width="50">
                            </a>

                        </div>
                        <div class="collapse navbar-collapse test" id="myNavbar">
                            <ul id="nav" class="nav navbar-nav">
                                <li class="hvr-underline-reveal"><a href="#">Home</a></li>
                                <li class="hvr-underline-reveal"><a href="#">Over ons</a></li>
                                <li class="hvr-underline-reveal"><a href="#">Contact</a></li>
                                <li class="hvr-underline-reveal"><a href="#">Advies</a></li>
                                <li class="hvr-underline-reveal"><a href="#">Partners</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="hvr-underline-reveal"><a href="#"><span class="glyphicon glyphicon-user"></span> Registreer verkoper</a></li>
                                <li class="hvr-underline-reveal"><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>

        <div class="row banner">
            <img alt="Banner" class="img-responsive" src="{% static 'master/img/banner/banner1.jpg' %}" height="1084">
            <div class=" col-sm-12 search-box">
                <div class=" container search-content">
                    <form role="form" class="form-horizontal">

                        <div class="form-group">
                            <div class="col-sm-8">
                                <label class="btn sofie-button-black"> Te koop</label>
                                <label class="btn sofie-button-black"> Te huur</label>
                            </div>
                        </div >

                        <div class="form-group">
                            <div class="col-sm-4 gen-field location-field">
                                <input type="email" class="form-control search-field" placeholder="Plaats, gemeente, postcode">
                            </div>

                             <div class="col-sm-2 gen-field">
                                <div class="input-group">
                                    <input type="text" ID="min-datebox" Class="form-control search-field" placeholder="Min prijs" >
                                    <div class="input-group-btn ">
                                        <button type="button" class="btn search-field dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" id="min-prijs">
                                            <li>500</li>
                                            <li>1000</li>
                                            <li>1500</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-2 gen-field">
                                <div class="input-group">
                                    <input type="text" ID="max-datebox" Class="form-control search-field" placeholder="Max prijs" >
                                    <div class="input-group-btn ">
                                        <button type="button" class="btn search-field dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" id="max-prijs">
                                            <li>1000</li>
                                            <li>1500</li>
                                            <li>2000</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-2 gen-field">
                                <select class="selectpicker " multiple title="Type pand" data-width="100%" >
                                    <option>Appartement</option>
                                    <option>Woning</option>
                                    <option>Duplex</option>
                                    <option>Studio</option>
                                    <option>Kot</option>
                                </select>
                            </div>

                            <div class="col-sm-2 gen-field submit-field">
                                 <button type="submit" class="btn sofie-button-black btn-block search-field">Zoeken</button>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-sm-6 col-sm-offset-3 ">
                                <button type="button" class="btn sofie-button-black btn-block">Uitgebreid zoeken</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">

            {% block content %}

            {%  include "master/testing/baseContent.html" %}
            {% endblock %}
        </div>

        <!-- FOOTER -->
        <div class="row">

            <footer class="footer-distributed">

					<div class="footer-left">

						<h3>Via<span>-Sofie</span></h3>

						<p class="footer-links">
							<a href="#">Home</a>
							·
							<a href="#">About</a>
							·
							<a href="#">Faq</a>
							·
							<a href="#">Contact</a>
						</p>

						<p class="footer-company-name">Via Sofie &copy; 2016</p>
					</div>

					<div class="footer-center">

						<div>
							<i class="fa fa-map-marker"></i>
							<p><span>21 jump Street</span> Somewhere, In France</p>
						</div>

						<div>
							<i class="fa fa-phone"></i>
							<p>+1 555 123456</p>
						</div>

						<div>
							<i class="fa fa-envelope"></i>
							<p><a href="#">support@company.com</a></p>
						</div>
					</div>

					<div class="footer-right">

						<p class="footer-disclaimer">
							<span>Disclaimer</span>
							Don't open the cookie jar. If you do the cookie monster will come out.
							And no I won't help you because i warned you not to open the cookie jar.
						</p>

						<div class="footer-icons">

							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-linkedin"></i></a>
							<a href="#"><i class="fa fa-github"></i></a>

						</div>

					</div>

				</footer>

        </div>

    </div>











	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js" ></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" > </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>


    <!--- Eigen JS -->
    <script src="{% static 'master/js/base/base.js' %}" > </script>
</body>

</html>

Viasofie/templates/master/testing/baseContent.html
<div class="col-sm-12 content">
        <div class="col-sm-4">
            <div class="pop-pand" >
                <p> IK BEN EEN POPULAIRE PAND </p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="pop-pand" >
                <p> IK BEN EEN POPULAIRE PAND </p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="pop-pand" >
                <p> IK BEN EEN POPULAIRE PAND </p>
            </div>
        </div>
</div>

Viasofie/templates/master/testing/detail.html
<h1> Detail testing:  Detail Huis </h1>


<h2><p>    {{pand.straat_naam}} {{pand.postcode}} {{pand.stad}}</p></h2>
<h4><p>{{pand.beschrijving|linebreaksbr}}</p></h4>



{% if  pand.pandreview_set.all %}

    <p>Met volgende reviews:</p>
        {% for pandReview in pand.pandreview_set.all %}
            <ul>
                    <li>  Pand {{ pandReview.pand.id }} |  Review auteur: {{pandReview.review.review_naam}} | Review: {{pandReview.review.review_text}}      </li>

            </ul>

        {% endfor %}
{% else %}
<p> pand heeft geen review<br/> voeg wat reviews toe </p>
{% endif %}

<!-- _______________________________________-->

{% if pand.pandcriteria_set.all %}
    <p> Met de volgende criteria</p>
     {% for pandCriteria in pand.pandcriteria_set.all %}

        <ul>
                <li>{{pandCriteria.aantal}} {{pandCriteria.criteria.naam}} </li>

        </ul>

    {% endfor %}
{% else %}
    <p> pand heeft geen criteria's. voeg wat criteria's toe </p>

{% endif %}

Viasofie/templates/master/testing/favorietepanden.html
<html>
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link href="{% static 'master/css/content/carousel.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous">
	</script>
    <script src="{% static 'master/js/carousel.js' %}"></script>
</head>



<div class="container">
  <div class="row">
    <div class="col-md-13">
      <div class="carousel slide multi-item-carousel" id="theCarousel">
        <div class="carousel-inner">
          <div class="item active">
            {% for pand in alle_panden%}
                <div class="col-xs-4"><a href="/pand/{{pand.pk}}"><img src="{{ MEDIA_URL }}{{pand.profiel_foto}}" class="img-responsive"></a></div>
            {% endfor %}
          </div>
          <div class="item notactive">

          </div>
          <div class="item notactive">

          </div>
          <div class="item notactive">

          </div>
          <div class="item notactive">

          </div>
          <div class="item notactive">

          </div>
        </div>
        <a class="left carousel-control" href="#theCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
        <a class="right carousel-control" href="#theCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
      </div>
    </div>
  </div>
</div>





</html>

Viasofie/templates/master/testing/index.html
<h1> Testing Panden </h1>

{% if alle_panden %}			<!-- Zolang ze minstens 1 pand hebben -->

	<h1> Alle huizen </h1>
        <ul>
            {% for pand in alle_panden%}
               <li> <p>{{pand.straat_naam}} {{pand.huis_nummer}} {{pand.postcode}} {{pand.stad}} staat {{pand.status}}
                   <a href=" /test/{{pand.id}}/">Details</a> </p></li>
            {% endfor %}
        </ul>

{%else %}					<!-- Als ze geen pand heeft -->
	<h3>Geen panden in database. Gelieve een pand toe te voegen </h3>

{% endif %}

Viasofie/templates/master/testing/lol.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>